package com.roberts.demo.com.roberts.dataAccess;

import com.roberts.demo.com.roberts.domain.Blog;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * This is an interface that describes a class that will connect with the database. The Spring Boot framework
 * will look at the methods defined in this interface, and generate a class with the correct SQL queries inside them.
 * This allows other object to reference the methods within this interface as if this interface were an already instantiated
 * object.
 */
public interface BlogRepository extends JpaRepository<Blog, Integer> {

	/**
	 * This is a method definition for a method that contains a sql query that finds all blog posts where the title contains
	 * the text within the first parameter, or the content contains the text within the second parameter. This method is
	 * automatically generated by the Spring Boot framework. It knows how to make the query based on the method name.
	 **/
	List<Blog> findAllByTitleContainingOrContentContaining(String text, String textAgain);
}
